export const SG_COURTS = [
  { name: "ACE The Place CC", area: "Woodlands", region: "North" },
  { name: "ActiveSG Sport Park @ Bedok North", area: "Bedok", region: "East" },
  { name: "ActiveSG Sport Village @ Jurong Town", area: "Jurong West", region: "West" },
  { name: "Admiralty Primary School Hall", area: "Woodlands", region: "North" },
  { name: "Ahmad Ibrahim Secondary School Hall", area: "Yishun", region: "North" },
  { name: "Anchor Green Primary School Hall", area: "Sengkang", region: "North-East" },
  { name: "Anchorvale CC", area: "Sengkang", region: "North-East" },
  { name: "Ang Mo Kio CC", area: "Ang Mo Kio", region: "North-East" },
  { name: "Ang Mo Kio Primary School Hall", area: "Ang Mo Kio", region: "North-East" },
  { name: "Ang Mo Kio Secondary School Hall", area: "Ang Mo Kio", region: "North-East" },
  { name: "Anglo Chinese School (ACS)", area: "Novena", region: "Central" },
  { name: "Ayer Rajah CC", area: "Clementi", region: "West" },
  { name: "Balestier Badminton Court", area: "Kallang", region: "Central" },
  { name: "Beacon Primary School Hall", area: "Bukit Panjang", region: "West" },
  { name: "Beatty Secondary School Hall", area: "Toa Payoh", region: "Central" },
  { name: "Bedok CC", area: "Bedok", region: "East" },
  { name: "Bedok Green Primary School Hall", area: "Bedok", region: "East" },
  { name: "Bedok South Secondary School Hall", area: "Bedok", region: "East" },
  { name: "Bendemeer Primary School Hall", area: "Kallang", region: "Central" },
  { name: "Bendemeer Secondary School Hall", area: "Kallang", region: "Central" },
  { name: "Bidadari CC", area: "Bishan", region: "Central" },
  { name: "Bishan ActiveSG Sports Hall", area: "Bishan", region: "Central" },
  { name: "Bishan CC", area: "Bishan", region: "Central" },
  { name: "Bishan Clubhouse", area: "Bishan", region: "Central" },
  { name: "Blangah Rise Primary School Hall", area: "Bukit Merah", region: "Central" },
  { name: "Boon Lay CC", area: "Boon Lay", region: "West" },
  { name: "Boon Lay Secondary School Hall", area: "Boon Lay", region: "West" },
  { name: "Bowen Secondary School Hall", area: "Hougang", region: "North-East" },
  { name: "Braddell Heights CC", area: "Serangoon", region: "North-East" },
  { name: "Buangkok CC", area: "Sengkang", region: "North-East" },
  { name: "Bukit Batok CC", area: "Bukit Batok", region: "West" },
  { name: "Bukit Canberra ActiveSG Sports Hall", area: "Sembawang", region: "North" },
  { name: "Bukit Gombak ActiveSG Sports Hall", area: "Bukit Batok", region: "West" },
  { name: "Bukit Panjang CC", area: "Bukit Panjang", region: "West" },
  { name: "Bukit Panjang Govt High School Hall", area: "Bukit Panjang", region: "West" },
  { name: "Bukit Panjang Primary School Hall", area: "Bukit Panjang", region: "West" },
  { name: "Bukit Timah CC", area: "Bukit Timah", region: "Central" },
  { name: "Bukit Timah Primary School Hall", area: "Bukit Timah", region: "Central" },
  { name: "Bukit View Secondary School Hall", area: "Bukit Batok", region: "West" },
  { name: "Buona Vista CC", area: "Queenstown", region: "Central" },
  { name: "Cairnhill CC", area: "Tanglin", region: "Central" },
  { name: "Canberra CC", area: "Sembawang", region: "North" },
  { name: "Canberra Primary School Hall", area: "Sembawang", region: "North" },
  { name: "Canberra Secondary School Hall", area: "Sembawang", region: "North" },
  { name: "Cantonment Primary School Hall", area: "Bukit Merah", region: "Central" },
  { name: "Casuarina Primary School Hall", area: "Pasir Ris", region: "East" },
  { name: "Cedar Primary School Hall", area: "Toa Payoh", region: "Central" },
  { name: "Cereza Sports Hall", area: "Geylang", region: "Central" },
  { name: "Changi Airport Recreation Club", area: "Changi", region: "East" },
  { name: "Changi Simei CC", area: "Tampines", region: "East" },
  { name: "Changkat Changi Secondary School Hall", area: "Tampines", region: "East" },
  { name: "Changkat Primary School Hall", area: "Tampines", region: "East" },
  { name: "Cheng San CC", area: "Ang Mo Kio", region: "North-East" },
  { name: "CHIJ St. Theresa's Convent Hall", area: "Bukit Merah", region: "Central" },
  { name: "Choa Chu Kang ActiveSG Sports Hall", area: "Choa Chu Kang", region: "West" },
  { name: "Chongfu Primary School Hall", area: "Yishun", region: "North" },
  { name: "Christ Church Secondary School Hall", area: "Woodlands", region: "North" },
  { name: "Chua Chu Kang CC", area: "Choa Chu Kang", region: "West" },
  { name: "Chua Chu Kang Secondary School Hall", area: "Choa Chu Kang", region: "West" },
  { name: "City Sprouts @ Bedok", area: "Bedok", region: "East" },
  { name: "Clementi ActiveSG Sports Hall", area: "Clementi", region: "West" },
  { name: "Clementi CC", area: "Clementi", region: "West" },
  { name: "Clementi Primary School Hall", area: "Clementi", region: "West" },
  { name: "Clementi Town Secondary School Hall", area: "Clementi", region: "West" },
  { name: "Commonwealth Secondary School Hall", area: "Jurong East", region: "West" },
  { name: "Community Hall @ Sprout Hub", area: "Bukit Merah", region: "Central" },
  { name: "Compassvale Primary School Hall", area: "Sengkang", region: "North-East" },
  { name: "Concord Primary School Hall", area: "Choa Chu Kang", region: "West" },
  { name: "Crescent Girls' School Hall", area: "Bukit Merah", region: "Central" },
  { name: "CSC Tessensohn", area: "Kallang", region: "Central" },
  { name: "Dazhong Primary School Hall", area: "Bukit Batok", region: "West" },
  { name: "Delta ActiveSG Sports Hall", area: "Bukit Merah", region: "Central" },
  { name: "Deyi Secondary School Hall", area: "Ang Mo Kio", region: "North-East" },
  { name: "Dover Court International School", area: "Queenstown", region: "Central" },
  { name: "Dunearn Secondary School Hall", area: "Bukit Batok", region: "West" },
  { name: "Dunman High School Hall", area: "Kallang", region: "Central" },
  { name: "East Spring Primary School Hall", area: "Tampines", region: "East" },
  { name: "Edgefield Primary School Hall", area: "Punggol", region: "North-East" },
  { name: "Edgefield Secondary School Hall", area: "Punggol", region: "North-East" },
  { name: "Elias Park Primary School Hall", area: "Pasir Ris", region: "East" },
  { name: "Endeavour Primary School Hall", area: "Sembawang", region: "North" },
  { name: "Eunoia Junior College Hall", area: "Bishan", region: "Central" },
  { name: "Eunos CC", area: "Bedok", region: "East" },
  { name: "Evergreen Primary School Hall", area: "Woodlands", region: "North" },
  { name: "Farrer Park Primary School Hall", area: "Kallang", region: "Central" },
  { name: "Fengshan CC", area: "Bedok", region: "East" },
  { name: "Fengshan Primary School Hall", area: "Bedok", region: "East" },
  { name: "Fern Green Primary School Hall", area: "Sengkang", region: "North-East" },
  { name: "Fernvale CC", area: "Hougang", region: "North-East" },
  { name: "Fernvale Village", area: "Sengkang", region: "North-East" },
  { name: "First Toa Payoh Primary School Hall", area: "Toa Payoh", region: "Central" },
  { name: "Frontier Primary School Hall", area: "Jurong West", region: "West" },
  { name: "Fuhua Secondary School Hall", area: "Jurong West", region: "West" },
  { name: "Gan Eng Seng Primary School Hall", area: "Bukit Merah", region: "Central" },
  { name: "Gek Poh Ville CC", area: "Jurong West", region: "West" },
  { name: "German European School (GESS)", area: "Bukit Panjang", region: "West" },
  { name: "Geylang Serai CC", area: "Geylang", region: "Central" },
  { name: "Geylang West CC", area: "Geylang", region: "Central" },
  { name: "Gongshang Primary School Hall", area: "Tampines", region: "East" },
  { name: "Greendale Primary School Hall", area: "Punggol", region: "North-East" },
  { name: "Greenridge Primary School Hall", area: "Bukit Panjang", region: "West" },
  { name: "Greenridge Secondary School Hall", area: "Bukit Panjang", region: "West" },
  { name: "Greenwood Primary School Hall", area: "Woodlands", region: "North" },
  { name: "Heartbeat @ Bedok ActiveSG Sports Hall", area: "Bedok", region: "East" },
  { name: "Henderson CC", area: "Bukit Merah", region: "Central" },
  { name: "Henry Park Primary School Hall", area: "Bukit Timah", region: "Central" },
  { name: "Hillgrove Secondary School Hall", area: "Bukit Batok", region: "West" },
  { name: "Hillview CC", area: "Bukit Timah", region: "Central" },
  { name: "HomeTeamNS Khatib", area: "Yishun", region: "North" },
  { name: "Hong Kah North CC", area: "Bukit Batok", region: "West" },
  { name: "Horizon Primary School Hall", area: "Punggol", region: "North-East" },
  { name: "Hougang ActiveSG Sports Hall", area: "Hougang", region: "North-East" },
  { name: "Hougang CC", area: "Hougang", region: "North-East" },
  { name: "Hougang Primary School Hall", area: "Hougang", region: "North-East" },
  { name: "Hougang Secondary School Hall", area: "Hougang", region: "North-East" },
  { name: "Hua Yi Secondary School Hall", area: "Jurong West", region: "West" },
  { name: "Hwi Yoh CC", area: "Serangoon", region: "North-East" },
  { name: "Innova Primary School Hall", area: "Woodlands", region: "North" },
  { name: "International Community School", area: "Clementi", region: "West" },
  { name: "Jalan Besar CC", area: "Kallang", region: "Central" },
  { name: "Jiemin Primary School Hall", area: "Yishun", region: "North" },
  { name: "Jing Shan Primary School Hall", area: "Ang Mo Kio", region: "North-East" },
  { name: "Joo Chiat CC", area: "Marine Parade", region: "Central" },
  { name: "Junyuan Primary School Hall", area: "Tampines", region: "East" },
  { name: "Junyuan Secondary School Hall", area: "Tampines", region: "East" },
  { name: "Jurong East ActiveSG Sports Hall", area: "Jurong East", region: "West" },
  { name: "Jurong Green CC", area: "Jurong West", region: "West" },
  { name: "Jurong Play Grounds", area: "Jurong East", region: "West" },
  { name: "Jurong Secondary School Hall", area: "Jurong West", region: "West" },
  { name: "Jurong Spring CC", area: "Jurong West", region: "West" },
  { name: "Jurong West ActiveSG Sports Hall", area: "Jurong West", region: "West" },
  { name: "Jurong West Primary School Hall", area: "Jurong West", region: "West" },
  { name: "Jurongville Secondary School Hall", area: "Jurong East", region: "West" },
  { name: "Kaki Bukit CC", area: "Bedok", region: "East" },
  { name: "Kallang CC", area: "Geylang", region: "Central" },
  { name: "Kampong Glam CC", area: "Kallang", region: "Central" },
  { name: "Kampong Kembangan CC", area: "Bedok", region: "East" },
  { name: "Kampong Ubi CC", area: "Geylang", region: "Central" },
  { name: "Keat Hong CC", area: "Choa Chu Kang", region: "West" },
  { name: "Kebun Baru CC", area: "Ang Mo Kio", region: "North-East" },
  { name: "Keming Primary School Hall", area: "Bukit Batok", region: "West" },
  { name: "KFF Badminton Arena", area: "Geylang", region: "Central" },
  { name: "Kim Seng CC", area: "Bukit Merah", region: "Central" },
  { name: "Kolam Ayer CC", area: "Kallang", region: "Central" },
  { name: "Kreta Ayer CC", area: "Outram", region: "Central" },
  { name: "Kuo Chuan Presbyterian Primary School Hall", area: "Bishan", region: "Central" },
  { name: "Lakeside Primary School Hall", area: "Jurong West", region: "West" },
  { name: "Leng Kee CC", area: "Bukit Merah", region: "Central" },
  { name: "Lianhua Primary School Hall", area: "Bukit Batok", region: "West" },
  { name: "Loyang View Secondary School Hall", area: "Pasir Ris", region: "East" },
  { name: "MacPherson CC", area: "Paya Lebar", region: "East" },
  { name: "Mapletree Business City Badminton Hall", area: "Queenstown", region: "Central" },
  { name: "Marsiling CC", area: "Sembawang", region: "North" },
  { name: "Marsiling Primary School Hall", area: "Woodlands", region: "North" },
  { name: "Marsiling Secondary School Hall", area: "Woodlands", region: "North" },
  { name: "Marymount CC", area: "Bishan", region: "Central" },
  { name: "Mayflower Secondary School Hall", area: "Ang Mo Kio", region: "North-East" },
  { name: "Meridian Primary School Hall", area: "Pasir Ris", region: "East" },
  { name: "Meridian Secondary School Hall", area: "Pasir Ris", region: "East" },
  { name: "MOE (Evans) ActiveSG Sports Hall", area: "Tanglin", region: "Central" },
  { name: "Mountbatten CC", area: "Marine Parade", region: "Central" },
  { name: "Nanyang CC", area: "Jurong West", region: "West" },
  { name: "Nanyang Primary School Hall", area: "Bukit Timah", region: "Central" },
  { name: "Naval Base Secondary School Hall", area: "Yishun", region: "North" },
  { name: "Nee Soon East CC", area: "Yishun", region: "North" },
  { name: "Nee Soon South CC", area: "Yishun", region: "North" },
  { name: "New Town Primary School Hall", area: "Queenstown", region: "Central" },
  { name: "New Town Secondary School Hall", area: "Queenstown", region: "Central" },
  { name: "North View Primary School Hall", area: "Yishun", region: "North" },
  { name: "North Vista Primary School Hall", area: "Sengkang", region: "North-East" },
  { name: "North Vista Secondary School Hall", area: "Sengkang", region: "North-East" },
  { name: "Northland Primary School Hall", area: "Yishun", region: "North" },
  { name: "Northland Secondary School Hall", area: "Yishun", region: "North" },
  { name: "Northoaks Primary School Hall", area: "Sembawang", region: "North" },
  { name: "NUS Multipurpose Sports Hall", area: "Clementi", region: "West" },
  { name: "NUS University Town, Stephen Riady Centre", area: "Queenstown", region: "Central" },
  { name: "Oasis Primary School Hall", area: "Punggol", region: "North-East" },
  { name: "OBA Arena @ Pasir Ris", area: "Pasir Ris", region: "East" },
  { name: "OBA Arena @ Punggol", area: "Punggol", region: "North-East" },
  { name: "OCBC Arena", area: "Kallang", region: "Central" },
  { name: "Our Tampines Hub", area: "Tampines", region: "East" },
  { name: "Palm View Primary School Hall", area: "Sengkang", region: "North-East" },
  { name: "Park View Primary School Hall", area: "Pasir Ris", region: "East" },
  { name: "Pasir Ris ActiveSG Sports Hall", area: "Pasir Ris", region: "East" },
  { name: "Pasir Ris Crest Secondary School Hall", area: "Pasir Ris", region: "East" },
  { name: "Pasir Ris East CC", area: "Pasir Ris", region: "East" },
  { name: "Pasir Ris Elias CC", area: "Pasir Ris", region: "East" },
  { name: "Pasir Ris Secondary School Hall", area: "Tampines", region: "East" },
  { name: "Paya Lebar Kovan CC", area: "Hougang", region: "North-East" },
  { name: "Peicai Secondary School Hall", area: "Serangoon", region: "North-East" },
  { name: "Peirce Secondary School Hall", area: "Bishan", region: "Central" },
  { name: "Peiying Primary School Hall", area: "Yishun", region: "North" },
  { name: "Pek Kio CC", area: "Kallang", region: "Central" },
  { name: "Pioneer Primary School Hall", area: "Jurong West", region: "West" },
  { name: "Poi Ching School Hall", area: "Tampines", region: "East" },
  { name: "Potong Pasir CC", area: "Toa Payoh", region: "Central" },
  { name: "Punggol Secondary School Hall", area: "Punggol", region: "North-East" },
  { name: "Punggol View Primary School Hall", area: "Punggol", region: "North-East" },
  { name: "Qifa Primary School Hall", area: "Clementi", region: "West" },
  { name: "Qihua Primary School Hall", area: "Woodlands", region: "North" },
  { name: "Queenstown CC", area: "Queenstown", region: "Central" },
  { name: "Queenstown Primary School Hall", area: "Queenstown", region: "Central" },
  { name: "Queensway Secondary School Hall", area: "Queenstown", region: "Central" },
  { name: "Radin Mas CC", area: "Bukit Merah", region: "Central" },
  { name: "Radin Mas Primary School Hall", area: "Bukit Merah", region: "Central" },
  { name: "RED Quarters", area: "Kallang", region: "Central" },
  { name: "Red Swastika School Hall", area: "Bedok", region: "East" },
  { name: "Riverside Secondary School Hall", area: "Woodlands", region: "North" },
  { name: "Rivervale CC", area: "Sengkang", region: "North-East" },
  { name: "Rivervale Primary School Hall", area: "Sengkang", region: "North-East" },
  { name: "SAFRA Jurong", area: "Jurong West", region: "West" },
  { name: "SAFRA Mount Faber", area: "Bukit Merah", region: "Central" },
  { name: "SAFRA Tampines", area: "Tampines", region: "East" },
  { name: "SAFRA Toa Payoh", area: "Toa Payoh", region: "Central" },
  { name: "SBH East Coast @ EXPO", area: "Changi", region: "East" },
  { name: "Sembawang CC", area: "Sembawang", region: "North" },
  { name: "Sembawang Primary School Hall", area: "Sembawang", region: "North" },
  { name: "Seng Kang Primary School Hall", area: "Sengkang", region: "North-East" },
  { name: "Seng Kang Secondary School Hall", area: "Sengkang", region: "North-East" },
  { name: "Sengkang ActiveSG Sports Hall", area: "Sengkang", region: "North-East" },
  { name: "Sengkang CC", area: "Sengkang", region: "North-East" },
  { name: "Sengkang Green Primary School Hall", area: "Sengkang", region: "North-East" },
  { name: "Sengkang Secondary School Hall", area: "Sengkang", region: "North-East" },
  { name: "Senja-Cashew CC", area: "Bukit Panjang", region: "West" },
  { name: "Serangoon Garden Secondary School Hall", area: "Serangoon", region: "North-East" },
  { name: "Serangoon Secondary School Hall", area: "Hougang", region: "North-East" },
  { name: "Shuqun Primary School Hall", area: "Jurong West", region: "West" },
  { name: "SIA Sports Club", area: "Changi", region: "East" },
  { name: "Siglap CC", area: "Bedok", region: "East" },
  { name: "Singapore Badminton Hall (SBH) @ Geylang", area: "Geylang", region: "Central" },
  { name: "Smash Arena SG Badminton Hall", area: "Pioneer", region: "West" },
  { name: "South View Primary School Hall", area: "Choa Chu Kang", region: "West" },
  { name: "St Gabriel's Secondary School Hall", area: "Serangoon", region: "North-East" },
  { name: "St Patrick's School Hall", area: "Marine Parade", region: "Central" },
  { name: "St. Anthony's Primary School Hall", area: "Bukit Batok", region: "West" },
  { name: "SUTD Badminton Hall", area: "Changi", region: "East" },
  { name: "Swiss Cottage Secondary School Hall", area: "Bukit Batok", region: "West" },
  { name: "Taman Jurong CC", area: "Jurong East", region: "West" },
  { name: "Tampines Changkat CC", area: "Tampines", region: "East" },
  { name: "Tampines East CC", area: "Tampines", region: "East" },
  { name: "Tampines North CC", area: "Tampines", region: "East" },
  { name: "Tampines West CC", area: "Tampines", region: "East" },
  { name: "Tanglin CC", area: "Tanglin", region: "Central" },
  { name: "Tanjong Pagar CC", area: "Outram", region: "Central" },
  { name: "Teck Ghee CC", area: "Ang Mo Kio", region: "North-East" },
  { name: "Teck Ghee Primary School Hall", area: "Ang Mo Kio", region: "North-East" },
  { name: "Telok Blangah CC", area: "Bukit Merah", region: "Central" },
  { name: "Temasek Club", area: "Bukit Timah", region: "Central" },
  { name: "Tengah CC", area: "Choa Chu Kang", region: "West" },
  { name: "The Frontier CC", area: "Jurong West", region: "West" },
  { name: "The Sports Arina", area: "Changi", region: "East" },
  { name: "Thomson CC", area: "Bishan", region: "Central" },
  { name: "Tiong Bahru CC", area: "Outram", region: "Central" },
  { name: "Toa Payoh Central CC", area: "Toa Payoh", region: "Central" },
  { name: "Toa Payoh East CC", area: "Toa Payoh", region: "Central" },
  { name: "Toa Payoh South CC", area: "Toa Payoh", region: "Central" },
  { name: "Toa Payoh West CC", area: "Toa Payoh", region: "Central" },
  { name: "Townsville Primary School Hall", area: "Ang Mo Kio", region: "North-East" },
  { name: "TruSmash", area: "Jurong East", region: "West" },
  { name: "Ulu Pandan CC", area: "Queenstown", region: "Central" },
  { name: "United World College", area: "Tampines", region: "East" },
  { name: "Unity Primary School Hall", area: "Choa Chu Kang", region: "West" },
  { name: "Unity Secondary School Hall", area: "Choa Chu Kang", region: "West" },
  { name: "Waterway Primary School Hall", area: "Punggol", region: "North-East" },
  { name: "Wellington Primary School Hall", area: "Sembawang", region: "North" },
  { name: "West Coast CC", area: "Clementi", region: "West" },
  { name: "West View Primary School Hall", area: "Bukit Panjang", region: "West" },
  { name: "Westwood Secondary School Hall", area: "Jurong West", region: "West" },
  { name: "Whampoa CC", area: "Kallang", region: "Central" },
  { name: "Woodgrove Primary School Hall", area: "Woodlands", region: "North" },
  { name: "Woodgrove Secondary School Hall", area: "Woodlands", region: "North" },
  { name: "Woodlands ActiveSG Sports Hall", area: "Woodlands", region: "North" },
  { name: "Woodlands CC", area: "Woodlands", region: "North" },
  { name: "Woodlands Galaxy CC", area: "Woodlands", region: "North" },
  { name: "Woodlands Primary School Hall", area: "Woodlands", region: "North" },
  { name: "Woodlands Ring Primary School Hall", area: "Woodlands", region: "North" },
  { name: "Woodlands Secondary School Hall", area: "Woodlands", region: "North" },
  { name: "Wyse Active Hub", area: "Jurong East", region: "West" },
  { name: "Xing Hua Primary School Hall", area: "Hougang", region: "North-East" },
  { name: "Yangzheng Primary School Hall", area: "Serangoon", region: "North-East" },
  { name: "Yew Tee CC", area: "Choa Chu Kang", region: "West" },
  { name: "Yio Chu Kang ActiveSG Sports Hall", area: "Yio Chu Kang", region: "North-East" },
  { name: "Yio Chu Kang CC", area: "Ang Mo Kio", region: "North-East" },
  { name: "Yio Chu Kang Primary School Hall", area: "Hougang", region: "North-East" },
  { name: "Yio Chu Kang Secondary School Hall", area: "Ang Mo Kio", region: "North-East" },
  { name: "Yishun ActiveSG Sports Hall", area: "Yishun", region: "North" },
  { name: "Yishun Primary School Hall", area: "Yishun", region: "North" },
  { name: "Yishun Secondary School Hall", area: "Yishun", region: "North" },
  { name: "Yishun Town Secondary School Hall", area: "Yishun", region: "North" },
  { name: "Yuan Ching Secondary School Hall", area: "Jurong West", region: "West" },
  { name: "Yuhua CC", area: "Boon Lay", region: "West" },
  { name: "Zhenghua CC", area: "Bukit Panjang", region: "West" },
  { name: "Zhonghua Primary School Hall", area: "Serangoon", region: "North-East" }
];